"""add_side_column_to_mobile_suits.

Revision ID: 453f2bb7ec4e
Revises: 8c5469ea1ecd
Create Date: 2026-01-29 22:44:40.332325

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "453f2bb7ec4e"
down_revision: str | Sequence[str] | None = "8c5469ea1ecd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mobile_suits",
        sa.Column(
            "side",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="PLAYER",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mobile_suits", "side")
    # ### end Alembic commands ###
