"""add_environment_to_missions.

Revision ID: 46ebed749d6b
Revises: 9a8b7c6d5e4f
Create Date: 2026-02-08 15:45:16.872921

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46ebed749d6b"
down_revision: str | Sequence[str] | None = "9a8b7c6d5e4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "missions",
        sa.Column(
            "environment",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="SPACE",
            nullable=False,
        ),
    )
    op.add_column(
        "mobile_suits", sa.Column("terrain_adaptability", sa.JSON(), nullable=True)
    )
    op.alter_column(
        "mobile_suits",
        "tactics",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text(
            '\'{"priority": "CLOSEST", "range": "BALANCED"}\'::json'
        ),
    )
    op.drop_constraint(op.f("pilots_user_id_key"), "pilots", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("pilots_user_id_key"),
        "pilots",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "mobile_suits",
        "tactics",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text(
            '\'{"priority": "CLOSEST", "range": "BALANCED"}\'::json'
        ),
    )
    op.drop_column("mobile_suits", "terrain_adaptability")
    op.drop_column("missions", "environment")
    # ### end Alembic commands ###
