"""add_battle_room_and_entry_tables.

Revision ID: 4a1b2c3d4e5f
Revises: 27a590afd0ec
Create Date: 2026-02-05 12:10:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a1b2c3d4e5f"
down_revision: str | Sequence[str] | None = "2f18b99001c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### Create battle_rooms table ###
    op.create_table(
        "battle_rooms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_battle_rooms_status"), "battle_rooms", ["status"], unique=False
    )

    # ### Create battle_entries table ###
    op.create_table(
        "battle_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("mobile_suit_id", sa.Uuid(), nullable=False),
        sa.Column("mobile_suit_snapshot", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["room_id"], ["battle_rooms.id"]),
        sa.ForeignKeyConstraint(["mobile_suit_id"], ["mobile_suits.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_battle_entries_user_id"), "battle_entries", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_battle_entries_room_id"), "battle_entries", ["room_id"], unique=False
    )
    op.create_index(
        op.f("ix_battle_entries_mobile_suit_id"),
        "battle_entries",
        ["mobile_suit_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_battle_entries_mobile_suit_id"), table_name="battle_entries")
    op.drop_index(op.f("ix_battle_entries_room_id"), table_name="battle_entries")
    op.drop_index(op.f("ix_battle_entries_user_id"), table_name="battle_entries")
    op.drop_table("battle_entries")
    op.drop_index(op.f("ix_battle_rooms_status"), table_name="battle_rooms")
    op.drop_table("battle_rooms")
    # ### end Alembic commands ###
