"""Initial migration.

Revision ID: 8c5469ea1ecd
Revises:
Create Date: 2026-01-23 16:40:52.340030

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c5469ea1ecd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mobile_suits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("max_hp", sa.Integer(), nullable=False),
        sa.Column("current_hp", sa.Integer(), nullable=False),
        sa.Column("armor", sa.Integer(), nullable=False),
        sa.Column("mobility", sa.Float(), nullable=False),
        sa.Column("sensor_range", sa.Float(), nullable=False),
        sa.Column("position", sa.JSON(), nullable=True),
        sa.Column("velocity", sa.JSON(), nullable=True),
        sa.Column("weapons", sa.JSON(), nullable=True),
        sa.Column("active_weapon_index", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mobile_suits_name"), "mobile_suits", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_mobile_suits_user_id"), "mobile_suits", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mobile_suits_user_id"), table_name="mobile_suits")
    op.drop_index(op.f("ix_mobile_suits_name"), table_name="mobile_suits")
    op.drop_table("mobile_suits")
    # ### end Alembic commands ###
