"""add_season_and_leaderboard_tables.

Revision ID: c3d4e5f6g7h8
Revises: 1cfa385ca4aa
Create Date: 2026-02-11 04:50:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3d4e5f6g7h8"
down_revision: str | Sequence[str] | None = "1cfa385ca4aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### Create seasons table ###
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_seasons_is_active"), "seasons", ["is_active"], unique=False)

    # ### Create leaderboards table ###
    op.create_table(
        "leaderboards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pilot_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("kills", sa.Integer(), nullable=False),
        sa.Column("credits_earned", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leaderboards_season_id"), "leaderboards", ["season_id"], unique=False)
    op.create_index(op.f("ix_leaderboards_user_id"), "leaderboards", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_leaderboards_user_id"), table_name="leaderboards")
    op.drop_index(op.f("ix_leaderboards_season_id"), table_name="leaderboards")
    op.drop_table("leaderboards")
    op.drop_index(op.f("ix_seasons_is_active"), table_name="seasons")
    op.drop_table("seasons")
    # ### end Alembic commands ###
